### ISSUE TITLE
Code Climate coverage false positives

### ISSUE THREAD

**Issue by Nogbit** [babel/6to5-library-boilerplate#115]
This problem existed before your switch to babel, and exists now.

Your code coverage summary generates the below output (note the 0/0 in the summary rows), yet, your icons in your readme indicate 100% coverage.  You get 100% coverage because at one time code climate was receiving actual data from your travis builds, but, it no longer does because the ``coverage/lcov.info`` is now empty in your builds.

```
----------|-----------|-----------|-----------|-----------|
File      |   % Stmts |% Branches |   % Funcs |   % Lines |
----------|-----------|-----------|-----------|-----------|
----------|-----------|-----------|-----------|-----------|
All files |       100 |       100 |       100 |       100 |
----------|-----------|-----------|-----------|-----------|


=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
================================================================================
```

The following is from Code Climate support.  I'm looking into a fix myself for my project, but in the meantime this should help you.

-----------------------------
Also, I took a look at your other repository: 6to5-library-boilerplate. It turns out that this same exact issue is occurring there as well. For example, for the latest Travis job, see Line 371: https://travis-ci.org/babel/6to5-library-boilerplate/builds/50725443#L371

That said, for 6to5-library-boilerplate, this didn't used to be case. I looked back through some of your old jobs in Travis, and I can see that up until Job 216, coverage data was being generated and sent to Code Climate just fine. For example, see Line 365 from Job 214: https://travis-ci.org/babel/6to5-library-boilerplate/builds/50718528#L365 For Job 214, note that the coverage summary indicates that a series of statements, branches, functions, and lines were indeed tested.

However, starting with Job 216, that's no longer the case, as 0/0 items are tested and the error from our reporter is being thrown: https://travis-ci.org/babel/6to5-library-boilerplate/builds/50719433#L365 So, something seems to have changed between Jobs 214 and 216, though I'm not sure exactly what changed.

**Comment by jmeas** [comment]
Ahhh. JSDom doesn't implement `Array.prototype.forEach`. Shucks.

I'll fix this up @Nogbit – thanks for the report!

**Comment by Nogbit** [comment]
It's not the name change since ``gulp coverage`` running locally (before and after name change) generates an empty ``coverage/lcov.info`` file.  

You would have the same problem on travis before or after the name change as you can see in this build a few days before the name change https://travis-ci.org/babel/6to5-library-boilerplate/builds/50725423, in that build you can't see an empty file, but, it's there becuase the 0/0 in the 3rd column for 100% of the rows of the coverage summary would result in an empty file.

**Comment by jmeas** [comment]
The issue here is that authoring the tests in ES6 messed up Istanbul. Both 6to5 and Istanbul overwrite Node's `require`, rather than wrapping it. So you can only have one or the other.

For now, I'll revert that change until I can come up with some clever way to make it work.

Thanks for the report @nogbit!

**Comment by jmeas** [comment]
Oh interesting. An app I'm working on has ES6 tests w. a very similar setup to this repo, and the coverage reports are being generated.

*maybe there **is** a way!*

**Comment by jmeas** [comment]
I asked @sebmck about the feasibility of this feature over at https://github.com/babel/babel/issues/660#issuecomment-74803690

**Comment by Nogbit** [comment]
Thanks!

**Comment by jmeas** [comment]
Thank *you* @Nogbit! I should have been paying more attention to the tests. :)
